In [1]:
import pandas as np
import numpy as np

In [8]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#load iris dataset
iris=datasets.load_iris()
x=iris.data
y=iris.target

#split data into train and test sets
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=40)

In [3]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [4]:
model = GradientBoostingClassifier(
    loss='log_loss',                 # Loss function to be optimized (default 'deviance', options: 'deviance', 'exponential')
    learning_rate=0.1,               # Learning rate shrinks the contribution of each tree (default 0.1)
    n_estimators=100,                # The number of boosting stages to be run (default 100)
    subsample=1.0,                   # The fraction of samples to be used for fitting the individual base learners (default 1.0)
    criterion='friedman_mse',        # The function to measure the quality of a split (default 'friedman_mse', options: 'friedman_mse', 'mse', 'mae')
    min_samples_split=2,             # The minimum number of samples required to split an internal node (default 2)
    min_samples_leaf=1,              # The minimum number of samples required to be at a leaf node (default 1)
    min_weight_fraction_leaf=0.0,    # The minimum weighted fraction of the sum total of weights required to be at a leaf node (default 0.0)
    max_depth=3,                     # The maximum depth of the individual base learners (default 3)
    min_impurity_decrease=0.0,       # A node will be split if this split induces a decrease of the impurity greater than or equal to this value (default 0.0)
    init=None,                       # An estimator object that is used to compute the initial predictions (default None)
    random_state=None,               # Controls the randomness of the estimator (default None)
    max_features=None,               # The number of features to consider when looking for the best split (default None)
    verbose=0,                       # The verbosity level (default 0)
    max_leaf_nodes=None,             # Grow trees with max_leaf_nodes in best-first fashion (default None)
    warm_start=False,                # When set to True, reuse the solution of the previous call to fit and add more estimators to the ensemble (default False)
    validation_fraction=0.1,         # The proportion of training data to set aside as validation set for early stopping (default 0.1)
    n_iter_no_change=None,           # Used to decide if early stopping will be used to terminate training when validation score is not improving (default None)
    tol=1e-4,                        # Tolerance for early stopping (default 1e-4)
    ccp_alpha=0.0                    # Complexity parameter used for Minimal Cost-Complexity Pruning (default 0.0)
)

In [5]:
model.fit(X_train,y_train)
y_pred=model.predict(X_test)


In [9]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [10]:
print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.23333333333333334
Confusion Matrix:
[[3 4 1]
 [4 1 7]
 [2 5 3]]
Classification Report:
              precision    recall  f1-score   support

           0       0.33      0.38      0.35         8
           1       0.10      0.08      0.09        12
           2       0.27      0.30      0.29        10

    accuracy                           0.23        30
   macro avg       0.24      0.25      0.24        30
weighted avg       0.22      0.23      0.23        30

